
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: May  3 2025 22:00:27 EDT (May  4 2025 02:00:27 UTC)

// Verification Directory fv/counter 

module counter(clk, reset, out, vgnd, vpwr);
  input clk, reset;
  output [1:0] out;
  input vgnd, vpwr;
  wire clk, reset;
  wire [1:0] out;
  wire vgnd, vpwr;
  wire GND, VDD, n_0, n_1;
  scs130hd_dfrtp_1 \count_out_reg[1] (.RESETB (reset), .CLK (clk), .D
       (n_1), .Q (out[1]), .vpwr (VDD), .vnb (GND), .vpb (VDD), .vgnd
       (GND));
  scs130hd_xor2_1 g21__2398(.A (out[0]), .B (out[1]), .X (n_1), .vpwr
       (VDD), .vnb (GND), .vpb (VDD), .vgnd (GND));
  scs130hd_dfrbp_1 \count_out_reg[0] (.RESETB (reset), .CLK (clk), .D
       (n_0), .Q (out[0]), .QN (n_0), .vpwr (VDD), .vnb (GND), .vpb
       (VDD), .vgnd (GND));
endmodule

